# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de8b2068b7c4a4b5af183892de58a23f3b98f07bc27bb50bf623406a9e60251336eaae9d4d464787c790d1818d411672e81ba989e11586aa88cb1e776d9fb93f
  FACEBOOK_ID: 305868826530615
  FACEBOOK_SECRET: 9d9895a065cad6d06532c8ea23300d3b
  AWS_ACCESS_KEY_ID: AKIAIBNUZRY77YQK5FQQ
  AWS_S3_BUCKET: chuckie
  AWS_SECRET_ACCESS_KEY: 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
test:
  FACEBOOK_ID: 305868826530615
  FACEBOOK_SECRET: 9d9895a065cad6d06532c8ea23300d3b
  AWS_ACCESS_KEY_ID: AKIAIBNUZRY77YQK5FQQ
  AWS_S3_BUCKET: chuckie
  AWS_SECRET_ACCESS_KEY: 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

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  FACEBOOK_ID: 1661854867448474
  FACEBOOK_SECRET: 1c466099fbf5b9a23147e086d81eae1c
  AWS_ACCESS_KEY_ID: AKIAIBNUZRY77YQK5FQQ
  AWS_S3_BUCKET: chuckie
  AWS_SECRET_ACCESS_KEY: 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
